disabled checking for updates if in NH
CompuCell3D/CompuCell3D pull request #396
Opened 2021-02-12 19:08 UTC by JulianoGianlupi

2021-02-14 01:06 UTC, CompuCell3D requested changes

2021-02-14 01:06 UTC, CompuCell3D commented on cc3d/player5/ViewManager/SimpleViewManager.py
> +        from os import environ
move import to the top of the file

2021-02-14 01:07 UTC, CompuCell3D commented on cc3d/player5/ViewManager/SimpleViewManager.py
> +        from os import environ
otherwise it looks good!

2021-02-15 23:06 UTC, tjsego approved these changes

2021-02-16 16:12 UTC, JulianoGianlupi commented on cc3d/player5/ViewManager/SimpleViewManager.py
> +        from os import environ
done

2021-02-17 19:09 UTC, JulianoGianlupi commented
@CompuCell3D @tjsego can we also push this change to v4.2.4? that way NH will get the pertinent update sooner

2021-03-03 14:38 UTC, merged