Removed stop_simulation in some demos
CompuCell3D/CompuCell3D pull request #450
Opened 2021-05-25 10:38 UTC by tjsego

Closes #366.

2021-05-25 14:11 UTC, JulianoGianlupi approved these changes

2021-05-29 19:30 UTC, CompuCell3D requested changes
I woudl leave the stop function. Curious what you think @tjsego

2021-05-29 19:30 UTC, CompuCell3D commented on CompuCell3D/core/Demos/bacterium_macrophage_new_style/Simulation/bacterium_macrophage_2D_steppables.py
> -
I would leave it here. I added it on purpose here to illustrate how to stop simulation. What do you think @tjsego ?

2021-05-30 17:04 UTC, tjsego commented
> I woudl leave the stop function. Curious what you think @tjsego

If the code is as intended, then that's fine with me. In this case, let's close this PR and close #366 accordingly.

2021-06-01 08:57 UTC, closed without merging