Code documentation, OpenMP implementation added for Reaction-Diffusion Finite Volume Solvers
CompuCell3D/CompuCell3D pull request #552
Opened 2022-06-13 18:38 UTC by DeconvFFT

This version adds documentation for Reaction-Diffusion Finite Volume Solvers inside PDE solvers and adds OpenMP support for parallel implementation in Reaction-Diffusion Finite Volume Solvers. Using OpenMP enables cross-platform support for parallel implementation which was lacking for the Parallel Patterns Library.

2022-06-13 19:40 UTC, DeconvFFT commented
@tjsego, I was able to remove build-related files.

2022-06-15 10:47 UTC, tjsego requested changes
Much better. Looks like there are some lingering files from installing into the source directory. Please remove the following from the changes: 

- GPUEnabled.h
- include/*
- post_install_tasks/*

Also, please restore core/CompuCell3D/plugins/MomentOfInertia/Makefile to an unchanged state.

2022-07-05 13:35 UTC, DeconvFFT commented
@tjsego, wrapped print statements in debug macro

2022-08-21 13:14 UTC, tjsego approved these changes

2022-08-21 13:14 UTC, merged