added new demos
CompuCell3D/CompuCell3D pull request #683
Opened 2023-11-18 22:09 UTC by maciekswat

added new demos for the new modules

2023-11-18 22:20 UTC, fyffep requested changes

2023-11-18 22:20 UTC, fyffep commented on CompuCell3D/core/Demos/SteppableDemos/PolygonInitializer/Simulation/cellsort_2D.xml
> +git fetch fork
Remove line

2023-11-18 22:20 UTC, fyffep commented on CompuCell3D/core/Demos/SteppableDemos/TubeInitializer/Simulation/cellsort_2D.xml
> +         <Width>2</Width>
Add the tag ``<NumSlices>8</NumSlices>`` inside ``Region``.

2023-11-18 22:20 UTC, fyffep commented on CompuCell3D/core/Demos/SteppableDemos/TubeInitializer/Simulation/cellsort_2D.xml
> +         <Width>2</Width>
Add the tag ``<NumSlices>10</NumSlices>`` inside ``Region``.

2023-11-18 22:20 UTC, fyffep commented on CompuCell3D/core/Demos/SteppableDemos/PolygonInitializer/Simulation/cellsort_2D.xml
> +<CompuCell3D>
Do you think we should add a comment at the top of each one like this?
``<!--See the documentation for more details: https://compucell3dreferencemanual.readthedocs.io/en/latest/polygon_initializer.html -->``
And, similarly, for tubes...
``<!--See the documentation for more details: https://compucell3dreferencemanual.readthedocs.io/en/latest/tube_initializer.html -->``

2023-11-18 23:10 UTC, maciekswat commented
I made the fixes and added comments - those are indeed useful

2023-11-18 23:19 UTC, merged

2023-11-18 23:20 UTC, fyffep commented
> I made the fixes and added comments - those are indeed useful

Great, I see the changes. ``NumSlices`` isn't there, but it's also an optional tag and described in the documentation anyway.

2023-11-19 00:16 UTC, maciekswat commented
oops I forgot to add it. We can make a note and add it next time