Feature/2.5 d
CompuCell3D/CompuCell3D pull request #715
Opened 2024-04-28 01:12 UTC by maciekswat

This implements 2.5D simulations.There is an example showing how to use it

2024-04-28 14:23 UTC, fyffep commented on CompuCell3D/core/CompuCell3D/Boundary/BoundaryStrategy.cpp
> +    CC3D_Log(LOG_DEBUG) << "\t\t\t\t\t\t\t CALLING SPECILIZED CONSTRUCTOR FOR BOUNDARY STRATEGY";
nit: Remove comments and change to SPECIALIZED

2024-04-28 14:25 UTC, fyffep commented on CompuCell3D/core/CompuCell3D/Boundary/BoundaryStrategy.cpp
> +        strategy_z = nullptr;
Nice. This seems to be the correct way since NULL is an integer whereas nullptr is a ptr.

2024-04-28 14:36 UTC, fyffep commented on CompuCell3D/core/CompuCell3D/Boundary/BoundaryStrategy.cpp
> +}
nit: Remove other comments too

2024-04-28 14:55 UTC, fyffep commented on CompuCell3D/core/Demos/Models/cellsort_2_5_D/Simulation/cellsort_2D.xml
> +        <DimensionType>2.5D</DimensionType>
Besides this line, is there anything else people should be aware of when creating/designing 2.5D simulations? It can go in the docs.

2024-04-28 15:03 UTC, fyffep commented
Can you tell me about the results I should expect for testing? 

![image](https://github.com/CompuCell3D/CompuCell3D/assets/79017811/4d16a349-c806-4c4e-9b88-6257393d0b1e)
![image](https://github.com/CompuCell3D/CompuCell3D/assets/79017811/262c47d5-53cd-43ed-aea3-123d21798395)

2024-05-03 16:57 UTC, tjsego requested changes
All in all looks good and runs well. But can at least some of the commented code be removed before merging?

2024-05-04 17:08 UTC, maciekswat commented
> Can you tell me about the results I should expect for testing?
If you run with the 2.5D setting on and switch to XZ view (in 2D you should expect that pixel copies will take place horizontally i.e. no cell is allowed to extent along the z-axis). If you turn this setting off you will see that pixel copies will happen along the z-axis as well.

2024-05-04 17:53 UTC, maciekswat commented
@fyffep @tjsego I think I addressed PR comments. Please take a look

2024-05-04 17:55 UTC, maciekswat commented
@fyffep I added more comments tot he demo - telling users what to look for

2024-05-04 22:52 UTC, fyffep reviewed
Thanks for the cleanup. It runs well on my machine.
I know that some of my comments were surface-level, but I hope to make more nuanced comments on PRs as I gain more experience.

2024-05-11 18:27 UTC, merged